package gui;

import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities.*;

/**
 * GUI panel for user
 */
public class ClientGUIPanel extends javax.swing.JPanel {

    public ClientGUIPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsButtonGroup = new javax.swing.ButtonGroup();
        trainScheduleRadioButton = new javax.swing.JRadioButton();
        stationTextField = new javax.swing.JTextField();
        stationLabel = new javax.swing.JLabel();
        trainSearchRadioButton = new javax.swing.JRadioButton();
        fromStationLabel = new javax.swing.JLabel();
        toStationLabel = new javax.swing.JLabel();
        fromStationTextField = new javax.swing.JTextField();
        toStationTextField = new javax.swing.JTextField();
        timeIntervalLabel = new javax.swing.JLabel();
        timeFromSpinner = new javax.swing.JSpinner();
        colonLabel = new javax.swing.JLabel();
        timeToSpinner = new javax.swing.JSpinner();
        showButton = new javax.swing.JButton();
        buyTicketButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        trainsTable = new javax.swing.JTable();
        resetButton = new javax.swing.JButton();

        optionsButtonGroup.add(trainScheduleRadioButton);
        trainScheduleRadioButton.setText("Расписание поездов по станции:");
        trainScheduleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainScheduleRadioButtonActionPerformed(evt);
            }
        });

        stationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationTextFieldActionPerformed(evt);
            }
        });

        stationLabel.setText("Станция:");

        optionsButtonGroup.add(trainSearchRadioButton);
        trainSearchRadioButton.setText("Поиск поезда:");
        trainSearchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainSearchRadioButtonActionPerformed(evt);
            }
        });

        fromStationLabel.setText("От:");

        toStationLabel.setText("До:");

        fromStationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromStationTextFieldActionPerformed(evt);
            }
        });

        timeIntervalLabel.setText("Временной интервал:");

        colonLabel.setText(":");

        showButton.setText("Показать");

        buyTicketButton.setText("Купить билет");
        buyTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTicketButtonActionPerformed(evt);
            }
        });

        trainsTable.setModel(new TrainsTableModel());
        jScrollPane1.setViewportView(trainsTable);

        jScrollPane2.setViewportView(jScrollPane1);

        resetButton.setText("Сбросить");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showButton)
                        .addGap(18, 18, 18)
                        .addComponent(buyTicketButton)
                        .addGap(18, 18, 18)
                        .addComponent(resetButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trainScheduleRadioButton)
                            .addComponent(trainSearchRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(stationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(stationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(fromStationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(fromStationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(toStationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(toStationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(timeIntervalLabel)
                        .addGap(18, 18, 18)
                        .addComponent(timeFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(colonLabel)
                        .addGap(18, 18, 18)
                        .addComponent(timeToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainScheduleRadioButton)
                    .addComponent(stationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stationLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainSearchRadioButton)
                    .addComponent(fromStationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromStationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toStationLabel)
                    .addComponent(toStationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeIntervalLabel)
                    .addComponent(timeFromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colonLabel)
                    .addComponent(timeToSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showButton)
                    .addComponent(buyTicketButton)
                    .addComponent(resetButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void trainScheduleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainScheduleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainScheduleRadioButtonActionPerformed

    private void stationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stationTextFieldActionPerformed

    private void fromStationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromStationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromStationTextFieldActionPerformed

    private void trainSearchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainSearchRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainSearchRadioButtonActionPerformed

    private void buyTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyTicketButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyTicketButton;
    private javax.swing.JLabel colonLabel;
    private javax.swing.JLabel fromStationLabel;
    private javax.swing.JTextField fromStationTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup optionsButtonGroup;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton showButton;
    private javax.swing.JLabel stationLabel;
    private javax.swing.JTextField stationTextField;
    private javax.swing.JSpinner timeFromSpinner;
    private javax.swing.JLabel timeIntervalLabel;
    private javax.swing.JSpinner timeToSpinner;
    private javax.swing.JLabel toStationLabel;
    private javax.swing.JTextField toStationTextField;
    private javax.swing.JRadioButton trainScheduleRadioButton;
    private javax.swing.JRadioButton trainSearchRadioButton;
    private javax.swing.JTable trainsTable;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                JFrame frame = new JFrame("Client");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(575, 600);
                frame.getContentPane().add(new JScrollPane(new ClientGUIPanel()));
                frame.setVisible(true);
            }
            
        });
    }

}
